export const BOOKINGS_STATS_CARDS = [
  {
    id: "todays-bookings",
    title: "Today's Bookings",
    value: "12",
    change: "+8%",
    period: "Total reservations",
    trend: "up",
    bgColor: "bg-blue-100/90 dark:bg-blue-900/30",
    borderColor: "border-b-blue-700 dark:border-b-blue-500",
    iconbgColor: "bg-blue-500/20 dark:bg-blue-900/90",
    iconColor: "text-blue-600 dark:text-blue-300",
    icon: "Users",
    changeColor: "text-green-500",
  },
  {
    id: "capacity",
    title: "Capacity",
    value: "85%",
    change: "+12%",
    period: "Tables occupied",
    trend: "up",
    bgColor: "bg-yellow-100/90 dark:bg-yellow-600/30",
    borderColor: "border-b-yellow-400 dark:border-b-yellow-300",
    iconColor: "text-yellow-500 dark:text-yellow-200",
    iconbgColor: "bg-yellow-500/20 dark:bg-yellow-600/70",
    icon: "UserPlus",
    changeColor: "text-green-500",
  },
  {
    id: "no-shows",
    title: "No-Shows",
    value: "2",
    change: "-25%",
    period: "This week",
    trend: "down",
    bgColor: "bg-green-100/90 dark:bg-green-700/30",
    borderColor: "border-b-green-500 dark:border-b-green-400",
    iconbgColor: "bg-green-500/20 dark:bg-green-700/70",
    iconColor: "text-green-500 dark:text-green-200",
    icon: "Clock",
    changeColor: "text-green-500",
  },
];

export const UPCOMING_BOOKINGS = [
  {
    id: 1,
    title: "Johnson Wedding",
    datetime: "2024-01-20 at 6:00 PM",
    guests: "150 guests",
    status: "Confirmed",
  },
  {
    id: 2,
    title: "Corporate Lunch",
    datetime: "2024-01-22 at 12:00 PM",
    guests: "50 guests",
    status: "Confirmed",
  },
  {
    id: 3,
    title: "Birthday Party",
    datetime: "2024-01-25 at 3:00 PM",
    guests: "25 guests",
    status: "Pending",
  },
  {
    id: 4,
    title: "Birthday Party",
    datetime: "2024-01-25 at 3:00 PM",
    guests: "25 guests",
    status: "Pending",
  },
];

export const CALENDAR_EVENTS = [
  {
    id: 1,
    title: "Johnson Wedding",
    date: "2025-06-19",
    type: "wedding",
    time: "6:00 PM",
    guests: 150,
  },
  {
    id: 2,
    title: "Birthday Party",
    date: "2025-06-22",
    type: "birthday",
    time: "3:00 PM",
    guests: 25,
  },
  {
    id: 3,
    title: "Birthday Party",
    date: "2025-06-24",
    type: "birthday",
    time: "3:00 PM",
    guests: 25,
  },
];
