export const LEADS_STATS_CARDS = [
  {
    id: "total-leads",
    title: "Total leads",
    value: "147",
    change: "+63%",
    period: "This month",
    trend: "up",
    bgColor: "bg-blue-100/90 dark:bg-blue-900/30",
    borderColor: "border-b-blue-700 dark:border-b-blue-500",
    iconbgColor: "bg-blue-500/20 dark:bg-blue-900/90",
    iconColor: "text-blue-600 dark:text-blue-300",
    icon: "Users",
    changeColor: "text-green-500",
  },
  {
    id: "new-leads",
    title: "New leads",
    value: "16",
    change: "+5%",
    period: "This month",
    trend: "up",
    bgColor: "bg-yellow-100/90 dark:bg-yellow-600/30",
    borderColor: "border-b-yellow-400 dark:border-b-yellow-300",
    iconColor: "text-yellow-500 dark:text-yellow-200",
    iconbgColor: "bg-yellow-500/20 dark:bg-yellow-600/70",
    icon: "UserPlus",
    changeColor: "text-green-500",
  },
  {
    id: "conversion-rate",
    title: "Conversion rate",
    value: "68%",
    change: "+13%",
    period: "This month",
    trend: "up",
    bgColor: "bg-green-100/90 dark:bg-green-700/30",
    borderColor: "border-b-green-500 dark:border-b-green-400",
    iconbgColor: "bg-green-500/20 dark:bg-green-700/70",
    iconColor: "text-green-500 dark:text-green-200",
    icon: "Clock",
    changeColor: "text-green-500",
  },
  {
    id: "total-value",
    title: "Total value",
    value: "$127K",
    change: "+19%",
    period: "This month",
    trend: "up",
    bgColor: "bg-pink-100/90 dark:bg-pink-700/30",
    borderColor: "border-b-pink-500 dark:border-b-pink-400",
    iconbgColor: "bg-pink-500/20 dark:bg-pink-700/70",
    iconColor: "text-pink-500 dark:text-pink-200",
    icon: "DollarSign",
    changeColor: "text-green-500",
  },
];

export const STATUS_OPTIONS = [
  "All Status",
  "New",
  "In progress",
  "Won",
  "Denied",
];

export const PRIORITY_OPTIONS = ["Priority", "HIGH", "MEDIUM", "LOW"];

export const LEADS_DATA = [
  {
    id: 1,
    name: "Emily Thompson",
    email: "emily.thompson@email.com",
    phone: "+1 (555) 123-4567",
    eventType: "Wedding",
    status: "New",
    inquiryDate: "2024-01-15",
    priority: "HIGH",
    source: "Website",
  },
  {
    id: 2,
    name: "James Wilson",
    email: "james.wilson@email.com",
    phone: "+1 (555) 234-5678",
    eventType: "Corporate",
    status: "In progress",
    inquiryDate: "2024-01-15",
    priority: "MEDIUM",
    source: "Referral",
  },
  {
    id: 3,
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    phone: "+1 (555) 345-6789",
    eventType: "Birthday",
    status: "Won",
    inquiryDate: "2024-01-15",
    priority: "HIGH",
    source: "Social Media",
  },
  {
    id: 4,
    name: "Emily Thompson",
    email: "emily.thompson@email.com",
    phone: "+1 (555) 123-4567",
    eventType: "Wedding",
    status: "New",
    inquiryDate: "2024-01-15",
    priority: "MEDIUM",
    source: "Website",
  },
  {
    id: 5,
    name: "James Wilson",
    email: "james.wilson@email.com",
    phone: "+1 (555) 234-5678",
    eventType: "Corporate",
    status: "In progress",
    inquiryDate: "2024-01-15",
    priority: "HIGH",
    source: "Referral",
  },
  {
    id: 6,
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    phone: "+1 (555) 345-6789",
    eventType: "Birthday",
    status: "Denied",
    inquiryDate: "2024-01-15",
    priority: "MEDIUM",
    source: "Social Media",
  },
  {
    id: 7,
    name: "Michael Rodriguez",
    email: "michael.rodriguez@email.com",
    phone: "+1 (555) 456-7890",
    eventType: "Anniversary",
    status: "New",
    inquiryDate: "2024-01-16",
    priority: "LOW",
    source: "Website",
  },
  {
    id: 8,
    name: "Lisa Anderson",
    email: "lisa.anderson@email.com",
    phone: "+1 (555) 567-8901",
    eventType: "Corporate",
    status: "In progress",
    inquiryDate: "2024-01-16",
    priority: "HIGH",
    source: "Referral",
  },
  {
    id: 9,
    name: "David Kim",
    email: "david.kim@email.com",
    phone: "+1 (555) 678-9012",
    eventType: "Wedding",
    status: "Won",
    inquiryDate: "2024-01-17",
    priority: "HIGH",
    source: "Social Media",
  },
  {
    id: 10,
    name: "Jennifer Brown",
    email: "jennifer.brown@email.com",
    phone: "+1 (555) 789-0123",
    eventType: "Birthday",
    status: "New",
    inquiryDate: "2024-01-17",
    priority: "MEDIUM",
    source: "Website",
  },
];
